// bjj-coach/mobile/app/(auth)/signup.tsx
import React, { useState } from 'react';
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  StyleSheet,
  Alert,
  KeyboardAvoidingView,
  Platform,
  ScrollView,
} from 'react-native';
import { useRouter } from 'expo-router';
import { useAuthStore } from '../../src/stores/auth';
import { colors } from '../../src/theme/colors';
import { fonts } from '../../src/theme/fonts';

const BELT_RANKS = ['White', 'Blue', 'Purple', 'Brown', 'Black'];
const DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

export default function SignupScreen() {
  const [step, setStep] = useState(1);

  // Step 1
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  // Step 2
  const [beltRank, setBeltRank] = useState('');
  const [experienceMonths, setExperienceMonths] = useState('');

  // Step 3
  const [selectedDays, setSelectedDays] = useState<string[]>([]);
  const [trainingTime, setTrainingTime] = useState('');

  // Step 4
  const [goals, setGoals] = useState('');

  const { signup, loading } = useAuthStore();
  const router = useRouter();

  function toggleDay(day: string) {
    setSelectedDays((prev) =>
      prev.includes(day) ? prev.filter((d) => d !== day) : [...prev, day]
    );
  }

  async function handleSubmit() {
    if (!goals.trim()) {
      Alert.alert('Error', 'Please describe your goals.');
      return;
    }
    try {
      await signup({
        email: email.trim(),
        password,
        name: name.trim(),
        belt_rank: beltRank,
        experience_months: parseInt(experienceMonths, 10) || 0,
        training_days: JSON.stringify(selectedDays),
        goals: goals.trim(),
      });
    } catch (error: any) {
      Alert.alert('Signup Failed', error?.response?.data?.error || 'Something went wrong. Please try again.');
    }
  }

  function handleNext() {
    if (step === 1) {
      if (!name.trim() || !email.trim() || !password.trim()) {
        Alert.alert('Error', 'Please fill in all fields.');
        return;
      }
      if (password.length < 6) {
        Alert.alert('Error', 'Password must be at least 6 characters.');
        return;
      }
    }
    if (step === 2 && !beltRank) {
      Alert.alert('Error', 'Please select your belt rank.');
      return;
    }
    setStep((s) => s + 1);
  }

  const stepTitles = ['', 'step1.profile', 'step2.experience', 'step3.schedule', 'step4.goals'];

  return (
    <KeyboardAvoidingView style={styles.root} behavior={Platform.OS === 'ios' ? 'padding' : undefined}>
      <ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled">
        <View style={styles.header}>
          <Text style={styles.title}>BJJ Coach</Text>
          <Text style={styles.subtitle}>New account — {step}/4</Text>
        </View>

        <View style={styles.window}>
          <View style={styles.titleBar}>
            <View style={styles.dots}>
              <View style={[styles.dot, { backgroundColor: colors.close }]} />
              <View style={[styles.dot, { backgroundColor: colors.minimize }]} />
              <View style={[styles.dot, { backgroundColor: colors.maximize }]} />
            </View>
            <Text style={styles.windowTitle}>{stepTitles[step]}</Text>
          </View>
          <View style={styles.windowBody}>
            {step === 1 && (
              <>
                <Text style={styles.label}>YOUR NAME</Text>
                <TextInput style={styles.input} value={name} onChangeText={setName} placeholder="John Doe" placeholderTextColor={colors.textMuted} autoCapitalize="words" />

                <Text style={styles.label}>EMAIL</Text>
                <TextInput style={styles.input} value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" autoCorrect={false} placeholder="you@example.com" placeholderTextColor={colors.textMuted} />

                <Text style={styles.label}>PASSWORD</Text>
                <TextInput style={styles.input} value={password} onChangeText={setPassword} secureTextEntry placeholder="min. 6 characters" placeholderTextColor={colors.textMuted} />
              </>
            )}

            {step === 2 && (
              <>
                <Text style={styles.label}>BELT RANK</Text>
                <View style={styles.chips}>
                  {BELT_RANKS.map((belt) => (
                    <TouchableOpacity
                      key={belt}
                      style={[styles.chip, beltRank === belt && styles.chipSelected]}
                      onPress={() => setBeltRank(belt)}
                    >
                      <Text style={[styles.chipText, beltRank === belt && styles.chipTextSelected]}>{belt}</Text>
                    </TouchableOpacity>
                  ))}
                </View>

                <Text style={styles.label}>MONTHS TRAINING</Text>
                <TextInput style={styles.input} value={experienceMonths} onChangeText={setExperienceMonths} keyboardType="number-pad" placeholder="e.g. 24" placeholderTextColor={colors.textMuted} />
              </>
            )}

            {step === 3 && (
              <>
                <Text style={styles.label}>TRAINING DAYS</Text>
                <View style={styles.chips}>
                  {DAYS.map((day) => (
                    <TouchableOpacity
                      key={day}
                      style={[styles.chip, selectedDays.includes(day) && styles.chipSelected]}
                      onPress={() => toggleDay(day)}
                    >
                      <Text style={[styles.chipText, selectedDays.includes(day) && styles.chipTextSelected]}>{day}</Text>
                    </TouchableOpacity>
                  ))}
                </View>

                <Text style={styles.label}>TYPICAL TRAINING TIME (optional)</Text>
                <TextInput style={styles.input} value={trainingTime} onChangeText={setTrainingTime} placeholder="e.g. 7:00 PM" placeholderTextColor={colors.textMuted} />
              </>
            )}

            {step === 4 && (
              <>
                <Text style={styles.label}>YOUR BJJ GOALS</Text>
                <TextInput
                  style={[styles.input, styles.textarea]}
                  value={goals}
                  onChangeText={setGoals}
                  multiline
                  numberOfLines={5}
                  placeholder="What do you want to achieve with BJJ? What are you working on?"
                  placeholderTextColor={colors.textMuted}
                  textAlignVertical="top"
                />
              </>
            )}

            <View style={styles.buttonRow}>
              {step > 1 && (
                <TouchableOpacity style={styles.backButton} onPress={() => setStep((s) => s - 1)}>
                  <Text style={styles.backText}>← Back</Text>
                </TouchableOpacity>
              )}
              {step < 4 ? (
                <TouchableOpacity style={styles.button} onPress={handleNext}>
                  <Text style={styles.buttonText}>> NEXT</Text>
                </TouchableOpacity>
              ) : (
                <TouchableOpacity style={[styles.button, loading && styles.buttonDisabled]} onPress={handleSubmit} disabled={loading}>
                  <Text style={styles.buttonText}>{loading ? 'Creating...' : '> CREATE ACCOUNT'}</Text>
                </TouchableOpacity>
              )}
            </View>

            {step === 1 && (
              <TouchableOpacity style={styles.link} onPress={() => router.push('/(auth)/login')}>
                <Text style={styles.linkText}>Have an account? Log in →</Text>
              </TouchableOpacity>
            )}
          </View>
        </View>
      </ScrollView>
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.dark },
  container: { flexGrow: 1, justifyContent: 'center', padding: 24 },
  header: { alignItems: 'center', marginBottom: 24 },
  title: { fontFamily: fonts.mono, fontSize: 22, color: colors.accent, letterSpacing: 2 },
  subtitle: { fontFamily: fonts.mono, fontSize: 11, color: colors.textMuted, marginTop: 4 },
  window: { borderRadius: 8, overflow: 'hidden', borderWidth: 1, borderColor: colors.surface },
  titleBar: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surface, paddingHorizontal: 12, paddingVertical: 10, gap: 8 },
  dots: { flexDirection: 'row', gap: 5 },
  dot: { width: 10, height: 10, borderRadius: 5 },
  windowTitle: { fontFamily: fonts.mono, fontSize: 12, color: colors.textMuted },
  windowBody: { backgroundColor: colors.parchment, padding: 20 },
  label: { fontFamily: fonts.mono, fontSize: 10, color: colors.textMuted, marginBottom: 6, marginTop: 14 },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 4,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    fontFamily: fonts.mono,
    color: colors.text,
    backgroundColor: colors.white,
  },
  textarea: { height: 120 },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
  },
  chipSelected: { backgroundColor: colors.dark, borderColor: colors.dark },
  chipText: { fontFamily: fonts.mono, fontSize: 13, color: colors.text },
  chipTextSelected: { color: colors.accent },
  buttonRow: { flexDirection: 'row', justifyContent: 'flex-end', gap: 12, marginTop: 20 },
  button: { backgroundColor: colors.dark, paddingVertical: 12, paddingHorizontal: 20, borderRadius: 4 },
  buttonDisabled: { opacity: 0.6 },
  buttonText: { fontFamily: fonts.mono, fontSize: 13, color: colors.accent, letterSpacing: 1 },
  backButton: { paddingVertical: 12, paddingHorizontal: 16 },
  backText: { fontFamily: fonts.mono, fontSize: 13, color: colors.textMuted },
  link: { marginTop: 16, alignItems: 'center' },
  linkText: { fontFamily: fonts.mono, fontSize: 12, color: colors.textMuted },
});

// bjj-coach/web/src/app/features/auth/signup.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AuthService, type SignupData } from '../../core/services/auth.service';

const BELT_OPTIONS = [
  { value: 'white', label: 'White', color: '#f0ece4', textColor: '#1a1a1a', border: true },
  { value: 'blue', label: 'Blue', color: '#3b82f6', textColor: '#fff', border: false },
  { value: 'purple', label: 'Purple', color: '#8b5cf6', textColor: '#fff', border: false },
  { value: 'brown', label: 'Brown', color: '#92400e', textColor: '#fff', border: false },
  { value: 'black', label: 'Black', color: '#1a1a1a', textColor: '#fff', border: false },
  { value: 'nogi', label: 'No-gi', color: '#2d3748', textColor: '#fff', border: false },
];

const EXPERIENCE_OPTIONS = [
  { value: 3, label: '< 6 months' },
  { value: 9, label: '6–12 months' },
  { value: 18, label: '1–2 years' },
  { value: 36, label: '2–5 years' },
  { value: 72, label: '5+ years' },
];

const DAYS = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'];
const DAY_LABELS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

@Component({
  selector: 'app-signup',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  template: `
    <div class="window-container">
      <div class="retro-window signup-window">
        <!-- Title bar -->
        <div class="retro-window__titlebar">
          <div class="retro-window__controls">
            <a routerLink="/" class="retro-window__dot retro-window__dot--close"></a>
            <span class="retro-window__dot retro-window__dot--minimize"></span>
            <span class="retro-window__dot retro-window__dot--maximize"></span>
          </div>
          <span class="retro-window__title">signup.wizard</span>
        </div>

        <div class="retro-window__body signup-body">
          <!-- Step indicator -->
          <div class="steps">
            <div class="step" *ngFor="let s of [1,2,3]; let i = index"
                 [class.step--active]="step === s"
                 [class.step--done]="step > s">
              <div class="step__circle">{{ step > s ? '✓' : s }}</div>
              <div class="step__label">{{ stepLabels[i] }}</div>
            </div>
            <div class="step__line"></div>
          </div>

          <!-- Step 1: Name + Email -->
          <div class="step-content" *ngIf="step === 1">
            <h2 class="step-title">Let's get you started</h2>
            <p class="step-desc">We just need a few basics to set up your coaching experience.</p>

            <div class="field">
              <label class="field-label">What should we call you?</label>
              <input type="text" class="field-input" [(ngModel)]="name" placeholder="Your name" autocomplete="name" />
            </div>

            <div class="field">
              <label class="field-label">Email</label>
              <input type="email" class="field-input" [(ngModel)]="email" placeholder="you@example.com" autocomplete="email" />
            </div>

            <div class="field">
              <label class="field-label">Password</label>
              <input type="password" class="field-input" [(ngModel)]="password" placeholder="At least 6 characters" autocomplete="new-password" />
            </div>
          </div>

          <!-- Step 2: Belt + Experience -->
          <div class="step-content" *ngIf="step === 2">
            <h2 class="step-title">Your BJJ background</h2>
            <p class="step-desc">This helps your coach tailor advice to your level.</p>

            <div class="field">
              <label class="field-label">Belt rank</label>
              <div class="chip-group">
                <button *ngFor="let b of beltOptions"
                        class="chip belt-chip"
                        [class.chip--selected]="beltRank === b.value"
                        [style.background]="beltRank === b.value ? b.color : 'transparent'"
                        [style.color]="beltRank === b.value ? b.textColor : 'var(--color-text-secondary)'"
                        [style.border-color]="beltRank === b.value ? b.color : ''"
                        (click)="beltRank = b.value">
                  {{ b.label }}
                </button>
              </div>
            </div>

            <div class="field">
              <label class="field-label">How long have you been training?</label>
              <div class="chip-group">
                <button *ngFor="let e of experienceOptions"
                        class="chip"
                        [class.chip--selected]="experienceMonths === e.value"
                        (click)="experienceMonths = e.value">
                  {{ e.label }}
                </button>
              </div>
            </div>
          </div>

          <!-- Step 3: Schedule + Goals -->
          <div class="step-content" *ngIf="step === 3">
            <h2 class="step-title">Training schedule & goals</h2>
            <p class="step-desc">When do you train? What are you working toward?</p>

            <div class="field">
              <label class="field-label">Training days</label>
              <div class="chip-group">
                <button *ngFor="let day of days; let i = index"
                        class="chip day-chip"
                        [class.chip--selected]="daySchedule[day]"
                        (click)="toggleDay(day)">
                  {{ dayLabels[i] }}
                </button>
              </div>
            </div>

            <div class="schedule-list" *ngIf="selectedDaysList.length > 0">
              <div class="schedule-row" *ngFor="let entry of selectedDaysList; trackBy: trackByDay">
                <span class="schedule-day">{{ entry.label }}</span>
                <input type="time" class="field-input time-input"
                       [ngModel]="daySchedule[entry.day]"
                       (ngModelChange)="daySchedule[entry.day] = $event" />
              </div>
            </div>

            <div class="field">
              <label class="field-label">What do you want to work on?</label>
              <textarea class="field-input field-textarea" [(ngModel)]="goals"
                        placeholder="e.g., Improve my guard retention, work on submissions from mount..."
                        rows="3"></textarea>
            </div>
          </div>

          <!-- Error message -->
          <p class="error-msg" *ngIf="errorMsg">{{ errorMsg }}</p>

          <!-- Navigation -->
          <div class="nav-buttons">
            <button class="btn-back" *ngIf="step > 1" (click)="step = step - 1">&larr; Back</button>
            <span class="nav-spacer"></span>
            <button class="btn-next" *ngIf="step < 3" (click)="nextStep()" [disabled]="!canAdvance()">
              Next &rarr;
            </button>
            <button class="btn-submit" *ngIf="step === 3" (click)="submit()" [disabled]="submitting">
              {{ submitting ? 'Creating account...' : 'Create account' }}
            </button>
          </div>

          <p class="login-link">
            Already have an account? <a routerLink="/auth/login">Sign in</a>
          </p>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .window-container {
      display: flex;
      justify-content: center;
      align-items: flex-start;
      padding: 24px 16px;
      min-height: calc(100vh - 52px);
    }
    .signup-window {
      width: 100%;
      max-width: 520px;
    }
    .signup-body {
      padding: 28px 24px;
      background: var(--color-surface-muted);
    }

    /* Steps indicator */
    .steps {
      display: flex;
      justify-content: center;
      gap: 40px;
      margin-bottom: 28px;
      position: relative;
    }
    .step {
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 6px;
      z-index: 1;
    }
    .step__circle {
      width: 32px;
      height: 32px;
      border-radius: 50%;
      border: 2px solid var(--color-window-border);
      background: var(--color-surface);
      display: flex;
      align-items: center;
      justify-content: center;
      font-family: var(--font-body);
      font-size: var(--text-sm);
      font-weight: 600;
      color: var(--color-text-muted);
      transition: all 0.2s;
    }
    .step--active .step__circle {
      border-color: var(--color-accent);
      background: var(--color-accent);
      color: var(--color-accent-text);
    }
    .step--done .step__circle {
      border-color: var(--color-success);
      background: var(--color-success);
      color: #fff;
      font-size: 14px;
    }
    .step__label {
      font-family: var(--font-body);
      font-size: var(--text-xs);
      color: var(--color-text-muted);
    }
    .step--active .step__label {
      color: var(--color-text);
      font-weight: 600;
    }
    .step__line {
      position: absolute;
      top: 16px;
      left: 25%;
      right: 25%;
      height: 2px;
      background: var(--color-window-border);
      z-index: 0;
    }

    /* Step content */
    .step-content {
      margin-bottom: 20px;
    }
    .step-title {
      font-family: var(--font-display);
      font-size: var(--text-xl);
      font-weight: 800;
      margin: 0 0 6px;
    }
    .step-desc {
      font-size: var(--text-sm);
      color: var(--color-text-secondary);
      margin: 0 0 20px;
    }

    /* Fields */
    .field {
      margin-bottom: 16px;
    }
    .field-label {
      display: block;
      font-family: var(--font-body);
      font-size: var(--text-sm);
      font-weight: 600;
      margin-bottom: 6px;
      color: var(--color-text);
    }
    .field-input {
      width: 100%;
      padding: 10px 14px;
      border: var(--border-subtle);
      border-radius: 6px;
      font-family: var(--font-body);
      font-size: var(--text-base);
      background: var(--color-surface);
      color: var(--color-text);
      outline: none;
      transition: border-color 0.15s;
    }
    .field-input:focus {
      border-color: var(--color-accent);
    }
    .field-textarea {
      resize: vertical;
      min-height: 72px;
    }
    .time-input {
      max-width: 160px;
    }
    .field-hint {
      font-size: var(--text-xs);
      color: var(--color-text-muted);
      margin-top: 4px;
    }

    /* Chips */
    .chip-group {
      display: flex;
      flex-wrap: wrap;
      gap: 8px;
    }
    .chip {
      padding: 6px 14px;
      border: var(--border-subtle);
      border-radius: 20px;
      background: transparent;
      font-family: var(--font-body);
      font-size: var(--text-sm);
      font-weight: 500;
      color: var(--color-text-secondary);
      cursor: pointer;
      transition: all 0.15s;
    }
    .chip:hover {
      border-color: var(--color-accent);
    }
    .chip--selected {
      background: var(--color-accent);
      color: var(--color-accent-text);
      border-color: var(--color-accent);
    }
    .belt-chip.chip--selected {
      border-color: rgba(0,0,0,0.2);
    }
    .day-chip {
      min-width: 48px;
      text-align: center;
    }

    /* Schedule list */
    .schedule-list {
      display: flex;
      flex-direction: column;
      gap: 8px;
      margin-top: 12px;
    }
    .schedule-row {
      display: flex;
      align-items: center;
      gap: 12px;
    }
    .schedule-day {
      font-family: var(--font-body);
      font-size: var(--text-sm);
      font-weight: 500;
      color: var(--color-text);
      min-width: 40px;
    }

    /* Error */
    .error-msg {
      color: var(--color-danger);
      font-size: var(--text-sm);
      margin-bottom: 12px;
      padding: 8px 12px;
      background: #fef2f2;
      border-radius: 6px;
      border: 1px solid #fecaca;
    }

    /* Navigation */
    .nav-buttons {
      display: flex;
      align-items: center;
      gap: 12px;
      margin-top: 4px;
    }
    .nav-spacer {
      flex: 1;
    }
    .btn-back {
      background: transparent;
      border: none;
      font-family: var(--font-body);
      font-size: var(--text-sm);
      font-weight: 500;
      color: var(--color-text-secondary);
      cursor: pointer;
      padding: 8px 4px;
    }
    .btn-back:hover {
      color: var(--color-text);
    }
    .btn-next, .btn-submit {
      background: var(--color-accent);
      color: var(--color-accent-text);
      border: 2px solid var(--color-text);
      border-radius: 6px;
      padding: 8px 20px;
      font-family: var(--font-body);
      font-size: var(--text-sm);
      font-weight: 600;
      cursor: pointer;
      transition: background 0.15s;
    }
    .btn-next:hover:not(:disabled), .btn-submit:hover:not(:disabled) {
      background: var(--color-accent-hover);
    }
    .btn-next:disabled, .btn-submit:disabled {
      opacity: 0.4;
      cursor: default;
    }
    .login-link {
      text-align: center;
      margin-top: 16px;
      font-size: var(--text-sm);
      color: var(--color-text-muted);
    }
    .login-link a {
      color: var(--color-accent-hover);
      text-decoration: none;
      font-weight: 600;
    }
    .login-link a:hover {
      text-decoration: underline;
    }

    @media (max-width: 480px) {
      .signup-body { padding: 20px 16px; }
      .steps { gap: 24px; }
      .step__line { left: 15%; right: 15%; }
    }
  `],
})
export class SignupComponent {
  step = 1;
  stepLabels = ['Basics', 'Background', 'Schedule'];

  // Step 1
  name = '';
  email = '';
  password = '';

  // Step 2
  beltRank = '';
  experienceMonths: number | null = null;
  beltOptions = BELT_OPTIONS;
  experienceOptions = EXPERIENCE_OPTIONS;

  // Step 3
  daySchedule: Record<string, string> = {};
  goals = '';
  days = DAYS;
  dayLabels = DAY_LABELS;

  // State
  submitting = false;
  errorMsg = '';

  constructor(private auth: AuthService, private router: Router) {}

  get selectedDaysList(): { day: string; label: string }[] {
    return this.days
      .filter(d => d in this.daySchedule)
      .map((d, _, __, i = this.days.indexOf(d)) => ({ day: d, label: DAY_LABELS[i] }));
  }

  trackByDay(_index: number, entry: { day: string }): string {
    return entry.day;
  }

  toggleDay(day: string): void {
    if (this.daySchedule[day]) {
      delete this.daySchedule[day];
    } else {
      this.daySchedule[day] = '19:00';
    }
  }

  canAdvance(): boolean {
    if (this.step === 1) {
      return this.name.trim().length > 0 && this.email.includes('@') && this.password.length >= 6;
    }
    if (this.step === 2) {
      return this.beltRank !== '' && this.experienceMonths !== null;
    }
    return true;
  }

  nextStep(): void {
    if (this.canAdvance()) {
      this.errorMsg = '';
      this.step++;
    }
  }

  submit(): void {
    this.errorMsg = '';
    this.submitting = true;

    const data: SignupData = {
      email: this.email.trim().toLowerCase(),
      password: this.password,
      name: this.name.trim(),
      belt_rank: this.beltRank,
      experience_months: this.experienceMonths || 0,
      training_days: JSON.stringify(this.daySchedule),
      goals: this.goals.trim(),
    };

    this.auth.signup(data).subscribe({
      next: () => {
        this.router.navigate(['/chat']);
      },
      error: (err) => {
        this.submitting = false;
        this.errorMsg = err.error?.error || 'Something went wrong. Please try again.';
      },
    });
  }
}
